apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nf4jpuooq-nodejs
  janus-idp.io/tekton: nf4jpuooq-nodejs
  backstage.io/kubernetes-id: nf4jpuooq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nf4jpuooq-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
