apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nf4jpuooq-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nf4jpuooq-nodejs 
  name: nf4jpuooq-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: nf4jpuooq-nodejs 
